=pod

=encoding utf8

=head1 NAME

go-online - Öffnet die Netzwerkverbindung

=head1 SYNOPSIS

B<go-online>

=head1 DESCRIPTION

Wrapper um die Netzwerkverbindung zu öffnen.
Nutzt z.Z. den I<NetworkManager(8)>.

Dies ist ein BASH-Skript.

=head1 FILES

=over

=item ~/.dont-go-online

=back

=head1 SEE ALSO

I<is-online(1p)>, I<go-offline(1p)>, I<is-offline(1p)>, I<nmcli(8)>

=cut

