=pod

=encoding utf8

=head1 NAME

is-offline - Testet die Netzwerkverbindung auf offline

=head1 SYNOPSIS

B<is-offline>

=head1 DESCRIPTION

Wrapper um zu testen, ob das System offline ist.
Nutzt z.Z. den I<NetworkManager(8)>.

Dies ist ein BASH-Skript.

=head1 EXIT STATUS

Der Rückgabewert ist 0 wenn offline und 1 wenn online.

=head1 SEE ALSO

I<go-online(1p)>, I<go-online(1p)>, I<is-online(1p)>, I<nm-online(8)>

=cut

