=pod

=encoding utf8

=head1 NAME

list-addresses - Zeigt IPv4-Adressen und verbundene Netzwerke an

=head1 SYNOPSIS

B<list-addresses> [--details]

=head1 DESCRIPTION

Zeigt IPv4-Adressen und verbundene Netzwerke an, wobei Interfaces die als
loopback und/oder down markiert sind ausgelassen werden.

=head1 OPTIONS

=over

=item --loopback

Zeigt auch als loopback markierte Interfaces an.

=item --down

Zeigt auch als down markierte Interfaces an.

=item --details

Zeigt den Namen und Details/Flags zum jeweiligen Interface an.

Ausgegeben werden die Flags in der Reihenfolge:

1) network block,
2) interface,
3) running,
4) broadcast,
5) pt2pt (point-to-point),
6) loopback,
7) promiscuous,
8) multicast,
9) notrailers,
10) noarp

	list-addresses --details | cut -f 2,1

=item --block

Netzwerk statt IP-Adresse ausgeben.

=back

=head1 SIEHE AUCH

L<IO::Interface::Simple(3pm)>, L<Net::Netmask(3pm)>

=cut

